name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
          persist-credentials: false

      - name: checkout build branch
        uses: actions/checkout@v4
        with:
          ref: build
          path: build
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: main/package-lock.json

      - name: npm ci and build
        run: |
          cd main
          npm ci
          npm run build
      
      - name: move files
        if: ${{ success() }}
        run: |
          rsync -a --exclude 'pr-preview' ./main/public/ ./build
      
      - name: Commit updates
        if: ${{ success() }}
        run: |
          cd build
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add changes"
        
      - name: Push changes to build
        if: ${{ success() }}
        uses: ad-m/github-push-action@master
        with:
          BRANCH: build
          directory: build
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
