name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: main
          persist-credentials: false

      - name: checkout build branch
        uses: actions/checkout@v2
        with:
          ref: build
          path: build
          persist-credentials: false

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # - name: npm install and build
      #   run: |
      #     cd temp
      #     npm install
      #     npm run build
      
      - name: move files
        if: ${{ success() }}
        run: |
          ls ./main
          echo "-----"
          ls ./build
      
      #    mv temp/public/* ./
      #    rm -rf temp
      # - name: Commit updates
      #   if: ${{ success() }}
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add .
      #     git commit -m "Add changes"
        
      # - name: Push changes
      #   if: ${{ success() }}
      #   uses: ad-m/github-push-action@master
      #   with:
      #     BRANCH: main
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     force: true